# Generated by Django 4.2.4 on 2023-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas1', '0005_rename_choise_text_choise_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
