# Generated by Django 4.2.4 on 2023-08-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas1', '0006_survey_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
